  GetTop:
  path: /top
  controller: App\Controller\FilmController::getTop
  methods: GET

GetFilm:
  path: /getfilm/{id}
  controller: App\Controller\FilmController::getFilm
  methods: GET

SetMark:
  path: /addmark/{id}
  controller: App\Controller\MarkController::setMark
  methods: GET

AddEpisode:
  path: /addepisode/{id}
  controller: App\Controller\FilmController::addEpisode
  methods: POST

CreateUser:
  path: /test
  controller: App\Controller\CreateUserController::test
  methods: GET

GetToken:
  path: /auth
  controller: App\Controller\GetTokenController::get_token
  methods: POST