GetTop:
  path: /top
  controller: App\Controller\FilmController::getTop
  methods: GET

GetFilm:
  path: /getfilm/{id}
  controller: App\Controller\FilmController::getFilm
  methods: GET

GetEpisode:
  path: /getepisode/{id}
  controller: App\Controller\FilmController::getEpisode
  methods: GET

SetMark:
  path: /addmark
  controller: App\Controller\MarkController::addMark
  methods: POST

AddEpisode:
  path: /addepisode/{id}
  controller: App\Controller\FilmController::addEpisode
  methods: POST

CreateUser:
  path: /registrate
  controller: App\Controller\CreateUserController::create_user
  methods: POST

GetToken:
  path: /auth
  controller: App\Controller\GetTokenController::get_token
  methods: POST